### ISSUE TITLE
python 3.4 for OSX is failing

### ISSUE THREAD

**Issue by ChayaSt** [choderalab/torsionfit#30]
Here's the travis failure:
https://travis-ci.org/choderalab/torsionfit/jobs/129268122#L173-L174

**Comment by jchodera** [comment]
We just ran into a similar problem with yank that was caused by a missing dependency on `anaconda` cloud. Can you just disable the `py34` test for now? 

The test ends up running for ~50 min, which takes up valuable travis time from other projects, so would be great if you could do this today!

**Comment by jchodera** [comment]
Actually, no need to do it today---I'll just disable the nightly builds for this project.

**Comment by ChayaSt** [comment]
Yes. I'll enable once I get back to this project and then deal with the issue of `py34`.
